[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Ensure GLB files are treated as binary and not processed
[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Content-Disposition = "inline"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

# More specific path-based header for GLB files
[[headers]]
  for = "/models/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Content-Disposition = "inline"
    X-Content-Type-Options = "nosniff"

# Don't process binary files
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 